// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjcpMdJO1i49MI8w5ZDu2figGD0rI6zO4',
    appId: '1:448140528590:web:cebe120ae0a2c8e88f399f',
    messagingSenderId: '448140528590',
    projectId: 'mychatapp-b89b3',
    authDomain: 'mychatapp-b89b3.firebaseapp.com',
    storageBucket: 'mychatapp-b89b3.appspot.com',
    measurementId: 'G-NN17FWF28R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXs9FKC7ee8vSIHfmsRGaZr94k8eXooVI',
    appId: '1:448140528590:android:711108991b2dfdde8f399f',
    messagingSenderId: '448140528590',
    projectId: 'mychatapp-b89b3',
    storageBucket: 'mychatapp-b89b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC8SRzx77DLZqrfCxuxy2uvWp9xgAlV3I',
    appId: '1:448140528590:ios:f2d7bffd781108db8f399f',
    messagingSenderId: '448140528590',
    projectId: 'mychatapp-b89b3',
    storageBucket: 'mychatapp-b89b3.appspot.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjcpMdJO1i49MI8w5ZDu2figGD0rI6zO4',
    appId: '1:448140528590:web:583aa6f224685d658f399f',
    messagingSenderId: '448140528590',
    projectId: 'mychatapp-b89b3',
    authDomain: 'mychatapp-b89b3.firebaseapp.com',
    storageBucket: 'mychatapp-b89b3.appspot.com',
    measurementId: 'G-3K3CB4L754',
  );
}
